// <auto-generated />
using System;
using Blanquita.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blanquita.Infrastructure.Persistence.Migrations.EF
{
    [DbContext(typeof(BlanquitaDbContext))]
    [Migration("20251228035752_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blanquita.Domain.Entities.CashCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[Mil] * 1000 + [Quinientos] * 500 + [Doscientos] * 200 + [Cien] * 100 + [Cincuenta] * 50 + [Veinte] * 20");

                    b.Property<string>("CashRegisterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Caja");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Cajera");

                    b.Property<DateTime>("CollectionDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHora");

                    b.Property<int>("Folio")
                        .HasColumnType("int");

                    b.Property<bool>("IsForCashCut")
                        .HasColumnType("bit")
                        .HasColumnName("Corte");

                    b.Property<string>("SupervisorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Encargada");

                    b.HasKey("Id");

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.ToTable("Recolecciones", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.CashCut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Sucursal");

                    b.Property<string>("CashRegisterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Caja");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Cajera");

                    b.Property<DateTime>("CutDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHora");

                    b.Property<int>("GranTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("[TotalM] * 1000 + [TotalQ] * 500 + [TotalD] * 200 + [TotalC] * 100 + [TotalCi] * 50 + [TotalV] * 20 + CAST([TotalTira] AS INT) + CAST([TotalTarjetas] AS INT)");

                    b.Property<string>("SupervisorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Encargada");

                    b.HasKey("Id");

                    b.ToTable("Cortes", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.CashRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("Sucursal");

                    b.Property<bool>("IsLastRegister")
                        .HasColumnType("bit")
                        .HasColumnName("Ultima");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cajas", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.Cashier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("Sucursal");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int")
                        .HasColumnName("NumNomina");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Edo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("Cajeras", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("Sucursal");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Edo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Encargadas", (string)null);
                });

            modelBuilder.Entity("Blanquita.Infrastructure.Persistence.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.CashCollection", b =>
                {
                    b.OwnsOne("Blanquita.Domain.ValueObjects.CashDenominations", "Denominations", b1 =>
                        {
                            b1.Property<int>("CashCollectionId")
                                .HasColumnType("int");

                            b1.Property<int>("Fifties")
                                .HasColumnType("int")
                                .HasColumnName("Cincuenta");

                            b1.Property<int>("FiveHundreds")
                                .HasColumnType("int")
                                .HasColumnName("Quinientos");

                            b1.Property<int>("Hundreds")
                                .HasColumnType("int")
                                .HasColumnName("Cien");

                            b1.Property<int>("Thousands")
                                .HasColumnType("int")
                                .HasColumnName("Mil");

                            b1.Property<int>("Twenties")
                                .HasColumnType("int")
                                .HasColumnName("Veinte");

                            b1.Property<int>("TwoHundreds")
                                .HasColumnType("int")
                                .HasColumnName("Doscientos");

                            b1.HasKey("CashCollectionId");

                            b1.ToTable("Recolecciones");

                            b1.WithOwner()
                                .HasForeignKey("CashCollectionId");
                        });

                    b.Navigation("Denominations")
                        .IsRequired();
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.CashCut", b =>
                {
                    b.OwnsOne("Blanquita.Domain.ValueObjects.CashCutTotals", "Totals", b1 =>
                        {
                            b1.Property<int>("CashCutId")
                                .HasColumnType("int");

                            b1.Property<int>("TotalFifties")
                                .HasColumnType("int")
                                .HasColumnName("TotalCi");

                            b1.Property<int>("TotalFiveHundreds")
                                .HasColumnType("int")
                                .HasColumnName("TotalQ");

                            b1.Property<int>("TotalHundreds")
                                .HasColumnType("int")
                                .HasColumnName("TotalC");

                            b1.Property<int>("TotalThousands")
                                .HasColumnType("int")
                                .HasColumnName("TotalM");

                            b1.Property<int>("TotalTwenties")
                                .HasColumnType("int")
                                .HasColumnName("TotalV");

                            b1.Property<int>("TotalTwoHundreds")
                                .HasColumnType("int")
                                .HasColumnName("TotalD");

                            b1.HasKey("CashCutId");

                            b1.ToTable("Cortes");

                            b1.WithOwner()
                                .HasForeignKey("CashCutId");

                            b1.OwnsOne("Blanquita.Domain.ValueObjects.Money", "TotalCards", b2 =>
                                {
                                    b2.Property<int>("CashCutTotalsCashCutId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("TotalTarjetas");

                                    b2.HasKey("CashCutTotalsCashCutId");

                                    b2.ToTable("Cortes");

                                    b2.WithOwner()
                                        .HasForeignKey("CashCutTotalsCashCutId");
                                });

                            b1.OwnsOne("Blanquita.Domain.ValueObjects.Money", "TotalSlips", b2 =>
                                {
                                    b2.Property<int>("CashCutTotalsCashCutId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("TotalTira");

                                    b2.HasKey("CashCutTotalsCashCutId");

                                    b2.ToTable("Cortes");

                                    b2.WithOwner()
                                        .HasForeignKey("CashCutTotalsCashCutId");
                                });

                            b1.Navigation("TotalCards")
                                .IsRequired();

                            b1.Navigation("TotalSlips")
                                .IsRequired();
                        });

                    b.Navigation("Totals")
                        .IsRequired();
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.CashRegister", b =>
                {
                    b.OwnsOne("Blanquita.Domain.ValueObjects.PrinterConfiguration", "PrinterConfig", b1 =>
                        {
                            b1.Property<int>("CashRegisterId")
                                .HasColumnType("int");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("IpImpresora");

                            b1.Property<int>("Port")
                                .HasColumnType("int")
                                .HasColumnName("Port");

                            b1.HasKey("CashRegisterId");

                            b1.ToTable("Cajas");

                            b1.WithOwner()
                                .HasForeignKey("CashRegisterId");
                        });

                    b.Navigation("PrinterConfig")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Blanquita.Infrastructure.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Blanquita.Infrastructure.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blanquita.Infrastructure.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Blanquita.Infrastructure.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
