// <auto-generated />
using System;
using Blanquita.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blanquita.Infrastructure.Persistence.Migrations.EF
{
    [DbContext(typeof(BlanquitaDbContext))]
    [Migration("20260112154540_AddForeignKeyToCashierAndSupervisorBranch")]
    partial class AddForeignKeyToCashierAndSupervisorBranch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blanquita.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SeriesCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SeriesDevolucion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SeriesGlobal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sucursales", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.CashCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("CAST([Mil] * 1000 + [Quinientos] * 500 + [Doscientos] * 200 + [Cien] * 100 + [Cincuenta] * 50 + [Veinte] * 20 AS decimal(18,2))");

                    b.Property<string>("CashRegisterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Caja");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Cajera");

                    b.Property<DateTime>("CollectionDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHora");

                    b.Property<int>("Folio")
                        .HasColumnType("int");

                    b.Property<bool>("IsForCashCut")
                        .HasColumnType("bit")
                        .HasColumnName("Corte");

                    b.Property<string>("SupervisorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Encargada");

                    b.HasKey("Id");

                    b.HasIndex("CashRegisterName")
                        .HasDatabaseName("IX_Recolecciones_Caja");

                    b.HasIndex("CollectionDateTime")
                        .HasDatabaseName("IX_Recolecciones_FechaHora");

                    b.HasIndex("IsForCashCut")
                        .HasDatabaseName("IX_Recolecciones_Corte");

                    b.HasIndex("CashRegisterName", "CollectionDateTime", "IsForCashCut")
                        .HasDatabaseName("IX_Recolecciones_Caja_FechaHora_Corte");

                    b.ToTable("Recolecciones", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.CashCut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Sucursal");

                    b.Property<string>("CashRegisterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Caja");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Cajera");

                    b.Property<DateTime>("CutDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHora");

                    b.Property<decimal>("GranTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("CAST([TotalM] * 1000 + [TotalQ] * 500 + [TotalD] * 200 + [TotalC] * 100 + [TotalCi] * 50 + [TotalV] * 20 AS decimal(18,2))");

                    b.Property<string>("SupervisorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Encargada");

                    b.HasKey("Id");

                    b.HasIndex("BranchName")
                        .HasDatabaseName("IX_Cortes_Sucursal");

                    b.HasIndex("CashRegisterName")
                        .HasDatabaseName("IX_Cortes_Caja");

                    b.HasIndex("CutDateTime")
                        .HasDatabaseName("IX_Cortes_FechaHora");

                    b.HasIndex("CutDateTime", "CashRegisterName")
                        .HasDatabaseName("IX_Cortes_FechaHora_Caja");

                    b.ToTable("Cortes", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.CashRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("Sucursal");

                    b.Property<bool>("IsLastRegister")
                        .HasColumnType("bit")
                        .HasColumnName("Ultima");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Serie");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cajas", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.Cashier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("Sucursal");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int")
                        .HasColumnName("NumNomina");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Edo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("Cajeras", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.DetalleReporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caja")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Caja");

                    b.Property<decimal>("Devolucion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Devolucion");

                    b.Property<decimal>("Facturado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Facturado");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Fecha");

                    b.Property<int>("ReporteHistoricoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.Property<decimal>("VentaGlobal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VentaGlobal");

                    b.HasKey("Id");

                    b.HasIndex("ReporteHistoricoId");

                    b.ToTable("DetallesReporte", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.LabelDesign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BarcodeHeightInMm")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AlturaCodigoBarrasMm");

                    b.Property<int>("BarcodeWidth")
                        .HasColumnType("int")
                        .HasColumnName("AnchoCodigoBarras");

                    b.Property<decimal>("HeightInMm")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AltoMm");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("EsPredeterminado");

                    b.Property<decimal>("MarginLeftInMm")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MargenIzquierdoMm");

                    b.Property<decimal>("MarginTopInMm")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MargenSuperiorMm");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Orientacion");

                    b.Property<int>("PriceFontSize")
                        .HasColumnType("int")
                        .HasColumnName("TamañoFuentePrecio");

                    b.Property<int>("ProductCodeFontSize")
                        .HasColumnType("int")
                        .HasColumnName("TamañoFuenteCodigo");

                    b.Property<int>("ProductNameFontSize")
                        .HasColumnType("int")
                        .HasColumnName("TamañoFuenteNombre");

                    b.Property<decimal>("WidthInMm")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AnchoMm");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DiseñosEtiquetas", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.LabelElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BarWidth")
                        .HasColumnType("int")
                        .HasColumnName("AnchoBarra");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Contenido");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Tipo");

                    b.Property<int>("FontSize")
                        .HasColumnType("int")
                        .HasColumnName("TamañoFuente");

                    b.Property<decimal?>("HeightMm")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AltoMm");

                    b.Property<int>("LabelDesignId")
                        .HasColumnType("int")
                        .HasColumnName("DiseñoId");

                    b.Property<decimal>("XMm")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("XMm");

                    b.Property<decimal>("YMm")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("YMm");

                    b.HasKey("Id");

                    b.HasIndex("LabelDesignId");

                    b.ToTable("ElementosEtiqueta", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dpi")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ip");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Activa");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("Puerto");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Impresoras", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.ReporteHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaGeneracion");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Notas");

                    b.Property<string>("Sucursal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Sucursal");

                    b.Property<decimal>("TotalCorteManual")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalCorteManual");

                    b.Property<decimal>("TotalSistema")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalSistema");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_ReportesHistoricos_Fecha");

                    b.HasIndex("FechaGeneracion")
                        .HasDatabaseName("IX_ReportesHistoricos_FechaGeneracion");

                    b.HasIndex("Sucursal", "Fecha")
                        .HasDatabaseName("IX_ReportesHistoricos_Sucursal_Fecha");

                    b.ToTable("ReportesHistoricos", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("Sucursal");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Edo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Encargadas", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mgw10005Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Mgw10008Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Pos10041Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Pos10042Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Printer2Ip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Printer2Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Printer2Port")
                        .HasColumnType("int");

                    b.Property<string>("PrinterIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrinterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PrinterPort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Configuracion", (string)null);
                });

            modelBuilder.Entity("Blanquita.Infrastructure.Persistence.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.CashCollection", b =>
                {
                    b.OwnsOne("Blanquita.Domain.ValueObjects.CashDenominations", "Denominations", b1 =>
                        {
                            b1.Property<int>("CashCollectionId")
                                .HasColumnType("int");

                            b1.Property<int>("Fifties")
                                .HasColumnType("int")
                                .HasColumnName("Cincuenta");

                            b1.Property<int>("FiveHundreds")
                                .HasColumnType("int")
                                .HasColumnName("Quinientos");

                            b1.Property<int>("Hundreds")
                                .HasColumnType("int")
                                .HasColumnName("Cien");

                            b1.Property<int>("Thousands")
                                .HasColumnType("int")
                                .HasColumnName("Mil");

                            b1.Property<int>("Twenties")
                                .HasColumnType("int")
                                .HasColumnName("Veinte");

                            b1.Property<int>("TwoHundreds")
                                .HasColumnType("int")
                                .HasColumnName("Doscientos");

                            b1.HasKey("CashCollectionId");

                            b1.ToTable("Recolecciones");

                            b1.WithOwner()
                                .HasForeignKey("CashCollectionId");
                        });

                    b.Navigation("Denominations")
                        .IsRequired();
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.CashCut", b =>
                {
                    b.OwnsOne("Blanquita.Domain.ValueObjects.CashCutTotals", "Totals", b1 =>
                        {
                            b1.Property<int>("CashCutId")
                                .HasColumnType("int");

                            b1.Property<int>("TotalFifties")
                                .HasColumnType("int")
                                .HasColumnName("TotalCi");

                            b1.Property<int>("TotalFiveHundreds")
                                .HasColumnType("int")
                                .HasColumnName("TotalQ");

                            b1.Property<int>("TotalHundreds")
                                .HasColumnType("int")
                                .HasColumnName("TotalC");

                            b1.Property<int>("TotalThousands")
                                .HasColumnType("int")
                                .HasColumnName("TotalM");

                            b1.Property<int>("TotalTwenties")
                                .HasColumnType("int")
                                .HasColumnName("TotalV");

                            b1.Property<int>("TotalTwoHundreds")
                                .HasColumnType("int")
                                .HasColumnName("TotalD");

                            b1.HasKey("CashCutId");

                            b1.ToTable("Cortes");

                            b1.WithOwner()
                                .HasForeignKey("CashCutId");

                            b1.OwnsOne("Blanquita.Domain.ValueObjects.Money", "TotalCards", b2 =>
                                {
                                    b2.Property<int>("CashCutTotalsCashCutId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("TotalTarjetas");

                                    b2.HasKey("CashCutTotalsCashCutId");

                                    b2.ToTable("Cortes");

                                    b2.WithOwner()
                                        .HasForeignKey("CashCutTotalsCashCutId");
                                });

                            b1.OwnsOne("Blanquita.Domain.ValueObjects.Money", "TotalSlips", b2 =>
                                {
                                    b2.Property<int>("CashCutTotalsCashCutId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("TotalTira");

                                    b2.HasKey("CashCutTotalsCashCutId");

                                    b2.ToTable("Cortes");

                                    b2.WithOwner()
                                        .HasForeignKey("CashCutTotalsCashCutId");
                                });

                            b1.Navigation("TotalCards")
                                .IsRequired();

                            b1.Navigation("TotalSlips")
                                .IsRequired();
                        });

                    b.Navigation("Totals")
                        .IsRequired();
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.CashRegister", b =>
                {
                    b.OwnsOne("Blanquita.Domain.ValueObjects.PrinterConfiguration", "PrinterConfig", b1 =>
                        {
                            b1.Property<int>("CashRegisterId")
                                .HasColumnType("int");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("IpImpresora");

                            b1.Property<int>("Port")
                                .HasColumnType("int")
                                .HasColumnName("Port");

                            b1.HasKey("CashRegisterId");

                            b1.ToTable("Cajas");

                            b1.WithOwner()
                                .HasForeignKey("CashRegisterId");
                        });

                    b.Navigation("PrinterConfig")
                        .IsRequired();
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.DetalleReporte", b =>
                {
                    b.HasOne("Blanquita.Domain.Entities.ReporteHistorico", null)
                        .WithMany("Detalles")
                        .HasForeignKey("ReporteHistoricoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.LabelElement", b =>
                {
                    b.HasOne("Blanquita.Domain.Entities.LabelDesign", "LabelDesign")
                        .WithMany("Elements")
                        .HasForeignKey("LabelDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabelDesign");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Blanquita.Infrastructure.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Blanquita.Infrastructure.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blanquita.Infrastructure.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Blanquita.Infrastructure.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.LabelDesign", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("Blanquita.Domain.Entities.ReporteHistorico", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
